// Run against a started app, or use node tests/run-browser.cjs.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
 const page = await browser.newPage({viewport:{width:1440,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const waitCount = async (selector, count) => {await page.waitForFunction(({selector,count})=>document.querySelectorAll(selector).length===count,{selector,count});};
 const base=process.env.TEST_BASE_URL || 'http://localhost:3000';
 await page.goto(base);
 await page.getByRole('heading',{name:'What’s cooking today?'}).waitFor();
 await page.getByRole('textbox',{name:'Search recipes'}).fill('rajma');
 await waitCount('.recipe',1);
 await page.getByRole('textbox',{name:'Search recipes'}).fill('');
 await page.getByRole('button',{name:'+ paneer',exact:true}).click();
 await waitCount('.recipe',1); // soaked chilla excluded by time
 await page.getByRole('button',{name:'Save Masala Paneer Wrap',exact:true}).click();
 await page.reload();
 await page.getByRole('button',{name:'Unsave Masala Paneer Wrap',exact:true}).waitFor();
 await page.getByRole('combobox',{name:'Diet',exact:true}).selectOption('vegan');
 await waitCount('.recipe',4);
 await page.getByRole('combobox',{name:'Diet',exact:true}).selectOption('all');
 await page.getByRole('textbox',{name:'Available ingredients'}).fill('rice, tomato');
 // Stub the provider route to check generated recipe UX, not live AI quality.
 await page.route('**/api/generate',route=>route.fulfill({json:{title:'Test rice bowl',description:'A test recipe.',ingredients:['1 cup rice','2 tomatoes'],steps:['Rinse rice.','Cook until tender.'],prepTime:20,servings:2,nutrition:{calories:300,protein:8,fiber:4,fats:5}}}));
 await page.getByRole('button',{name:'Create with AI'}).click();
 await page.getByRole('heading',{name:'Test rice bowl'}).waitFor();
 assert.equal(await page.locator('.generated-recipe ol li').count(),2);
 await page.locator('.generated-recipe').getByRole('button',{name:'Save recipe',exact:true}).click();
 await page.locator('.generated-recipe').getByRole('button',{name:'Add ingredients to list'}).click();
 await page.goto(base+'/favorites');
 await page.getByRole('link',{name:'Test rice bowl'}).click();
 await page.getByRole('heading',{name:'Test rice bowl'}).waitFor();
 await page.goto(base+'/shopping-list');
 assert.equal(await page.locator('.shopping-item').count(),2);
 await page.getByRole('button',{name:'Check 1 cup rice',exact:true}).click();
 await page.getByRole('button',{name:'Check 2 tomatoes',exact:true}).click();
 await page.getByRole('button',{name:'Clear completed'}).click();
 await page.getByRole('heading',{name:'Your shopping list is empty'}).waitFor();
 await page.reload();
 await page.getByRole('heading',{name:'Your shopping list is empty'}).waitFor();
 await page.getByRole('textbox',{name:'Shopping item'}).fill('Lemons');
 await page.getByRole('button',{name:'Add item',exact:true}).click();
 assert.equal(await page.locator('.shopping-item').count(),1);
 await page.setViewportSize({width:390,height:844});
 await page.goto(base);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await page.getByRole('link',{name:'Saved recipes',exact:true}).waitFor();
 await page.screenshot({path:'/tmp/rasoi-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1050});
 await page.screenshot({path:'/tmp/rasoi-desktop.png',fullPage:true});
 assert.deepEqual(errors,[]);
 const invalid = await page.request.post(base+'/api/generate',{data:{ingredients:[1]}}); assert.equal(invalid.status(),400);
 const noKey = await page.request.post(base+'/api/generate',{data:{ingredients:['rice']}}); assert.equal(noKey.status(),503);
 const search = await page.request.post(base+'/api/recipes',{data:{ingredients:['paneer']}});assert.equal((await search.json()).recipes.length,2);
 const blocked = await page.request.get(base+'/api/favorites',{headers:{'x-user-email':'other@example.com'}});assert.equal(blocked.status(),401);
 console.log('PASS: search, ingredient matching, diet, favorites reload, generated recipe steps/save/reopen, shopping cleanup/manual entry, responsive layout, API validation and unsigned-user rejection.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
